name: Lint, test and build
on:
  push:
    branches-ignore:
      - 'main'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Staticcheck
        run: make install-linter-ci
      - name: Run Staticcheck
        run: make lint
    
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Run unit tests
        run: make test
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Build Go files
        run: make build
